# Generated by Django 5.1.1 on 2025-01-06 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportedCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the currency (e.g., US Dollar, Bitcoin).', max_length=50)),
                ('code', models.CharField(help_text='The currency code (e.g., USD, BTC, ETH).', max_length=10, unique=True)),
                ('currency_type', models.CharField(choices=[('fiat', 'Fiat'), ('crypto', 'Cryptocurrency')], help_text='Type of the currency (fiat or cryptocurrency).', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this currency is currently active.')),
            ],
        ),
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=8, default=0.0, help_text='Current balance in the wallet.', max_digits=20)),
                ('wallet_address', models.CharField(blank=True, help_text='Wallet address for cryptocurrency (only applicable for crypto wallets).', max_length=255, null=True)),
                ('encrypted_private_key', models.TextField(blank=True, help_text='Encrypted private key for cryptocurrency wallets.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the wallet was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the wallet was last updated.')),
                ('currency', models.ForeignKey(help_text='The currency associated with this wallet.', on_delete=django.db.models.deletion.CASCADE, to='wallets.supportedcurrency')),
                ('user', models.ForeignKey(help_text='The user who owns this wallet.', on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'currency')},
            },
        ),
    ]
