# Generated by Django 5.1.1 on 2024-10-16 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Unnamed Company', max_length=100)),
                ('company_website', models.URLField(blank=True, default='')),
                ('contact_email', models.EmailField(default='contact@example.com', max_length=254)),
                ('phone_number', models.CharField(blank=True, default='', max_length=15)),
                ('address', models.TextField(blank=True, default='')),
                ('apps_offered', models.JSONField(blank=True, default=list)),
                ('business_registration_number', models.CharField(blank=True, default='', max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='provider_logos/')),
                ('portfolio', models.JSONField(blank=True, default=list)),
                ('api_access_key', models.CharField(blank=True, default='', max_length=100)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('support_contact', models.EmailField(blank=True, default='', max_length=254)),
                ('compliance_status', models.CharField(blank=True, default='Pending', max_length=100)),
                ('app_store_links', models.JSONField(blank=True, default=list)),
                ('certifications', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_invisible', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
