# Generated by Django 5.1.1 on 2025-01-06 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the payment gateway (e.g., PayPal, Stripe, Bitcoin).', max_length=100, unique=True)),
                ('gateway_type', models.CharField(choices=[('fiat', 'Fiat'), ('crypto', 'Cryptocurrency')], default='fiat', help_text='Type of the payment gateway (fiat or cryptocurrency).', max_length=10)),
                ('module_path', models.CharField(help_text="Python module path to the gateway integration logic (e.g., 'payments.gateways.stripe').", max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the gateway is active and available for use.')),
                ('api_key', models.CharField(blank=True, help_text='API key for the payment gateway (if applicable).', max_length=255, null=True)),
                ('secret_key', models.CharField(blank=True, help_text='Secret key for the payment gateway (if applicable).', max_length=255, null=True)),
                ('additional_config', models.JSONField(blank=True, help_text='Additional configuration for the gateway (e.g., webhook URLs).', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(help_text='Unique identifier for the transaction.', max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=8, help_text='Transaction amount.', max_digits=20)),
                ('currency', models.CharField(help_text='Currency code (e.g., USD, EUR, BTC, ETH).', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', help_text='Status of the transaction.', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the transaction was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the transaction was last updated.')),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata related to the transaction (e.g., customer details).', null=True)),
                ('gateway', models.ForeignKey(help_text='The payment gateway used for this transaction.', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.paymentgateway')),
            ],
        ),
    ]
