# Generated by Django 5.1.1 on 2024-10-12 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_game', models.CharField(default='Unknown Game', max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='player_pics/')),
                ('bio', models.TextField(blank=True, default='No bio available.', max_length=500)),
                ('level', models.IntegerField(default=1)),
                ('achievements', models.JSONField(blank=True, default=dict)),
                ('social_links', models.JSONField(blank=True, default=dict)),
                ('game_preferences', models.JSONField(blank=True, default=list)),
                ('mobile_number', models.CharField(blank=True, default='Not provided', max_length=15)),
                ('location', models.CharField(blank=True, default='Unknown', max_length=100)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('is_subscribed', models.BooleanField(default=False)),
                ('receive_newsletter', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
