# Generated by Django 5.1.1 on 2024-10-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providerappoptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingStateStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('value', models.CharField(default='default_value', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Listing State Statuses',
            },
        ),
    ]
